force-app/main/default/objects/ChangeRequest__c/ChangeRequest__c.object-meta.xml
<CustomObject>
    <description>Objeto customizado para armazenar as solicitações de Devs para implantações (deploys) de mudanças.</description>
    <label>Solicitação de Mudança</label>
    <nameField>
        <label>Change Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitações de Mudanças</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChangeRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Opções de status para as solicitações de mudanças, varia de acordo com cada etapa da solicitação.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Pronto para aprovação</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Deployed</fullName>
                <label>Implantado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeRequestAPI.cls
@RestResource(urlMapping='/changerequests/*')
global with sharing class ChangeRequestAPI {

    @HttpGet
    global static ChangeRequest__c getChange() {
        RestRequest req = RestContext.request;
        String recId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        return [SELECT Id, Name, Status__c FROM ChangeRequest__c WHERE Id = :recId];
    }

    @HttpPost
    global static String createChange(ChangeRequest__c newCR) {
        insert newCR;
        return newCR.Id;
    }
}